sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t sparkubuntu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sparkubuntu/docker-react npm run test